food_sharing/WebApp/Areas/Admin/Controllers/CartController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Contracts.BLL.App;
using DAL.App.EF;
using Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IAppBLL _bll;
        private readonly Object[] _paymentMethods = {
            new { Name = "Swedbank"},
            new { Name = "SEB"},
            new { Name = "LHV pank"},
            new { Name = "Pocopay"},
            new { Name = "Nordea"},
            new { Name = "Coop"},
            new { Name = "Danske"},
        };
        
        public CartController(AppDbContext context, IAppBLL bll)
        {
            _context = context;
            _bll = bll;
        }

        // GET: Cart
        public async Task<IActionResult> Index()
        {
            var carts = await _bll.Carts.GetAllForViewAsync(User.UserId());
            return View(carts);
        }

        // GET: Cart/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _bll.Carts.FirstOrDefaultViewAsync(id.Value, User.UserId());

            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Cart/Create
        public async Task<IActionResult> Create()
        {
            ViewData["PaymentMethod"] = new SelectList(_paymentMethods, "Name", "Name");
            ViewData["RestaurantId"] = new SelectList(await _bll.Restaurants.GetAllAsyncBase(User.UserId()), "Id", "Location");
            ViewData["UserLocationId"] = new SelectList(await _bll.UserLocations.GetAllAsyncBase(User.UserId()), "Id", "FullName");
            ViewData["AppUserId"] = new SelectList(_context.Users.Where(user => user.Id == User.UserId()), "Id", "FirstName");
            return View();
        }

        // POST: Cart/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BLL.App.DTO.Cart cart)
        {
            if (ModelState.IsValid)
            {
                _bll.Carts.Add(cart);
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PaymentMethod"] = new SelectList(_paymentMethods, "Name", "Name");
            ViewData["RestaurantId"] = new SelectList(await _bll.Restaurants.GetAllAsyncBase(User.UserId()), "Id", "Location", cart.RestaurantId);
            ViewData["UserLocationId"] = new SelectList(await _bll.UserLocations.GetAllAsyncBase(User.UserId()), "Id", "FullName", cart.UserLocationId);
            ViewData["AppUserId"] = new SelectList(_context.Users.Where(user => user.Id == User.UserId()), "Id", "FirstName");
            return View(cart);
        }

        // GET: Cart/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _bll.Carts.FirstOrDefaultViewAsync(id.Value, User.UserId());

            if (cart == null)
            {
                return NotFound();
            }
            ViewData["PaymentMethod"] = new SelectList(_paymentMethods, "Name", "Name");
            ViewData["RestaurantId"] = new SelectList(await _bll.Restaurants.GetAllAsyncBase(User.UserId()), "Id", "Location", cart.RestaurantId);
            ViewData["UserLocationId"] = new SelectList(await _bll.UserLocations.GetAllAsyncBase(User.UserId()), "Id", "FullName", cart.UserLocationId);
            ViewData["AppUserId"] = new SelectList(_context.Users.Where(user => user.Id == User.UserId()), "Id", "FirstName");
            return View(cart);
        }

        // POST: Cart/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, BLL.App.DTO.Cart cart)
        {
            if (id != cart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _bll.Carts.UpdateAsync(cart);
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PaymentMethod"] = new SelectList(_paymentMethods, "Name", "Name");
            ViewData["RestaurantId"] = new SelectList(await _bll.Restaurants.GetAllAsyncBase(User.UserId()), "Id", "Location", cart.RestaurantId);
            ViewData["UserLocationId"] = new SelectList(await _bll.UserLocations.GetAllAsyncBase(User.UserId()), "Id", "FullName", cart.UserLocationId);
            ViewData["AppUserId"] = new SelectList(_context.Users.Where(user => user.Id == User.UserId()), "Id", "FirstName");
            return View(cart);
        }

        // GET: Cart/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _bll.Carts.FirstOrDefaultViewAsync(id.Value, User.UserId());

            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Cart/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _bll.Carts.RemoveAsync(id, User.UserId());
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

food_sharing/WebApp/Areas/Admin/Controllers/ItemController.cs
using System;
using System.Threading.Tasks;
using Contracts.BLL.App;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ItemController : Controller
    {
        private readonly IAppBLL _bll;

        public ItemController(IAppBLL bll)
        {
            _bll = bll;
        }

        // GET: Item
        public async Task<IActionResult> Index()
        {
            var items = await _bll.Items.GetAllForViewAsync();
            return View(items);
        }

        // GET: Item/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _bll.Items.FirstOrDefaultViewAsync(id.Value);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Item/Create
        public async Task<IActionResult> Create()
        {
            ViewData["SharingId"] = new SelectList(await _bll.Sharings.GetAllAsyncBase(), "Id", "Name");
            return View();
        }

        // POST: Item/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BLL.App.DTO.Item item)
        {
            if (ModelState.IsValid)
            {
                _bll.Items.Add(item);
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SharingId"] = new SelectList(await _bll.Sharings.GetAllAsyncBase(), "Id", "Name", item.SharingId);
            return View(item);
        }

        // GET: Item/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _bll.Items.FirstOrDefaultViewAsync(id.Value);

            if (item == null)
            {
                return NotFound();
            }
            ViewData["SharingId"] = new SelectList(await _bll.Sharings.GetAllAsyncBase(), "Id", "Name", item.SharingId);
            return View(item);
        }

        // POST: Item/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, BLL.App.DTO.Item item)
        {
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _bll.Items.UpdateAsync(item);
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SharingId"] = new SelectList(await _bll.Sharings.GetAllAsyncBase(), "Id", "Name", item.SharingId);
            return View(item);
        }

        // GET: Item/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _bll.Items.FirstOrDefaultViewAsync(id.Value);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Item/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _bll.Items.RemoveAsync(id);
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

food_sharing/WebApp/Areas/Admin/Controllers/PizzaController.cs
using System;
using System.Threading.Tasks;
using Contracts.BLL.App;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class PizzaController : Controller
    {
        private readonly IAppBLL _bll;

        public PizzaController(IAppBLL bll)
        {
            _bll = bll;
        }

        // GET: Pizza
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var pizzas = await _bll.Pizzas.GetAllForViewAsync();
            return View(pizzas);
        }

        // GET: Pizza/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizza = await _bll.Pizzas.FirstOrDefaultViewAsync(id.Value);
            
            if (pizza == null)
            {
                return NotFound();
            }

            return View(pizza);
        }

        // GET: Pizza/Create
        public async Task<IActionResult> Create()
        {
            ViewData["PizzaTemplateId"] = new SelectList(await _bll.PizzaTemplates.GetAllAsyncBase(), "Id", "Name");
            return View();
        }

        // POST: Pizza/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BLL.App.DTO.Pizza pizza)
        {
            if (ModelState.IsValid)
            {
                _bll.Pizzas.Add(pizza);
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PizzaTemplateId"] = new SelectList(await _bll.PizzaTemplates.GetAllAsyncBase(), "Id", "Name", pizza.PizzaTemplateId);
            return View(pizza);
        }

        // GET: Pizza/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizza = await _bll.Pizzas.FirstOrDefaultViewAsync(id.Value);
            
            if (pizza == null)
            {
                return NotFound();
            }
            ViewData["PizzaTemplateId"] = new SelectList(await _bll.PizzaTemplates.GetAllAsyncBase(), "Id", "Name", pizza.PizzaTemplateId);
            return View(pizza);
        }

        // POST: Pizza/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, BLL.App.DTO.Pizza pizza)
        {
            if (id != pizza.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _bll.Pizzas.UpdateAsync(pizza);
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PizzaTemplateId"] = new SelectList(await _bll.PizzaTemplates.GetAllAsyncBase(), "Id", "Name", pizza.PizzaTemplateId);
            return View(pizza);
        }

        // GET: Pizza/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizza = await _bll.Pizzas.FirstOrDefaultViewAsync(id.Value);

            if (pizza == null)
            {
                return NotFound();
            }

            return View(pizza);
        }

        // POST: Pizza/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _bll.Pizzas.RemoveAsync(id);
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

food_sharing/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
    <!--
    dropdown down arrow
    -->
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        -->
                        <!--
                        https://codedocu.com/Details?d=2212&a=9&f=367&l=0
                        -->
                        
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("admin"))
                        {
                            <div class="main_nav_dropdown">
                                <button class="main_nav_dropbtn">
                                    User
                                    <i class="fa fa-caret-down"></i>
                                </button>
                                <div class="main_nav_dropdown-content">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Cart" asp-action="Index">Cart</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="CartMeal" asp-action="Index">CartMeal</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Item" asp-action="Index">Item</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Sharing" asp-action="Index">Sharing</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="SharingItem" asp-action="Index">SharingItem</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="UserLocation" asp-action="Index">UserLocation</a>
                                </div>
                            </div>
                            <div class="main_nav_dropdown">
                                <button class="main_nav_dropbtn">
                                    Restaurant
                                    <i class="fa fa-caret-down"></i>
                                </button>
                                <div class="main_nav_dropdown-content">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Component" asp-action="Index">Component</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="ComponentPizzaTemplate" asp-action="Index">ComponentPizzaTemplate</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Pizza" asp-action="Index">Pizza</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="PizzaTemplate" asp-action="Index">PizzaTemplate</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Restaurant" asp-action="Index">Restaurant</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="RestaurantFood" asp-action="Index">RestaurantFood</a>
                                </div>
                            </div>
                            <div class="main_nav_dropdown">
                                <button class="main_nav_dropbtn">
                                    UserAPI
                                    <i class="fa fa-caret-down"></i>
                                </button>
                                <div class="main_nav_dropdown-content">
                                    <a class="nav-link text-dark" href="/api/v1.0/Cart">Cart</a>
                                    <a class="nav-link text-dark" href="/api/v1.0/CartMeal">CartMeal</a>
                                    <a class="nav-link text-dark" href="/api/v1.0/Item">Item</a>
                                    <a class="nav-link text-dark" href="/api/v1.0/Sharing">Sharing</a>
                                    <a class="nav-link text-dark" href="/api/v1.0/SharingItem">SharingItem</a>
                                    <a class="nav-link text-dark" href="/api/v1.0/UserLocation">UserLocation</a>
                                </div>
                            </div>
                            <div class="main_nav_dropdown">
                                <button class="main_nav_dropbtn">
                                    RestaurantAPI
                                    <i class="fa fa-caret-down"></i>
                                </button>
                                <div class="main_nav_dropdown-content">
                                    <a class="nav-link text-dark" href="/api/v1.0/Component">Component</a>
                                    <a class="nav-link text-dark" href="/api/v1.0/ComponentPizzaTemplate">ComponentPizzaTemplate</a>
                                    <a class="nav-link text-dark" href="/api/v1.0/Pizza">Pizza</a>
                                    <a class="nav-link text-dark" href="/api/v1.0/PizzaTemplate">PizzaTemplate</a>
                                    <a class="nav-link text-dark" href="/api/v1.0/Restaurant">Restaurant</a>
                                    <a class="nav-link text-dark" href="/api/v1.0/RestaurantFood">RestaurantFood</a>
                                </div>
                            </div>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>